name: Push and Scheduled Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 9 * * *'   # Har roz subah 9 baje UTC time me chalega

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "✅ Code Updated / Scheduled Run"
