name: Push and Scheduled Workflow

on:
  push:
    branches:
      - main

  schedule:
<<<<<<< HEAD
    -cron: '2 * * * *'
=======
    - cron: '2 * * * *'   # Har roz subah 9 baje UTC time me chalega
>>>>>>> refs/remotes/origin/main

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "✅ Code Updated / Scheduled Run"
