name: Print Message on Push

on:
  push:
    branches:
      - main  # Jab koi main branch me push kare

  schedule:
    -cron: '5 * * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print code updated message
        run: echo "✅ Code Updated"
